/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useBox } from '@react-three/cannon';
import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import { useConfiguredGLTF } from '../../../hooks/useConfiguredGLTF';

export default function RoadIntersection(props) {
  const { nodes, materials } = useConfiguredGLTF(`road/road-inter.glb`);

  const [group] = useBox(() => ({
    ...props,
  }));
  return (
    <mesh ref={group} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.0005]}>
        <group
          position={[0, 0, -178.69]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[579.23, 289.6, 473.07]}
        >
          <mesh material={materials.BANQUET_XC} geometry={nodes.Mesh004.geometry} />
          <mesh material={materials.CALLASFL_1} geometry={nodes.Mesh004_1.geometry} />
        </group>
      </group>
    </mesh>
  );
}

// useGLTF.preload(`road/road-inter.glb`);
