/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import { getPublicPath } from '../../../../utils/getPublicPath';

type GLTFResult = GLTF & {
  nodes: {
    Rectangle040: THREE.Mesh;
  };
  materials: {
    ['01 - Default']: THREE.MeshStandardMaterial;
  };
};

export default function BackWindows(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(`${getPublicPath()}/3d/common/back-window.glb`) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['01 - Default']}
        geometry={nodes.Rectangle040.geometry}
        position={[1.23, -0.04, 4.55]}
        rotation={[0, 1.57, 0]}
        scale={[0.005, 0.005, 0.005]}
      />
    </group>
  );
}

useGLTF.preload(`${getPublicPath()}/3d/common/back-window.glb`);
