/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import { getPublicPath } from '../../../../utils/getPublicPath';

type GLTFResult = GLTF & {
  nodes: {
    Object006: THREE.Mesh;
    Object007: THREE.Mesh;
  };
  materials: {
    ['07 - Default2']: THREE.MeshStandardMaterial;
    ['20 - Default']: THREE.MeshStandardMaterial;
  };
};

export default function Floor(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(`${getPublicPath()}/3d/common/floor.glb`) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['07 - Default2']}
        geometry={nodes.Object006.geometry}
        position={[0.11, -1, -2.48]}
        scale={[0.005, 0.005, 0.005]}
      />
      <mesh
        material={materials['20 - Default']}
        geometry={nodes.Object007.geometry}
        position={[0.11, -1, -2.48]}
        scale={[0.005, 0.005, 0.005]}
      />
    </group>
  );
}

useGLTF.preload(`${getPublicPath()}/3d/common/ceiling.glb`);
