/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import { getPublicPath } from '../../../../utils/getPublicPath';

type GLTFResult = GLTF & {
  nodes: {
    Mesh003: THREE.Mesh;
    Mesh003_1: THREE.Mesh;
    Mesh003_2: THREE.Mesh;
    Mesh003_3: THREE.Mesh;
  };
  materials: {
    ['10 - Default']: THREE.MeshStandardMaterial;
    ['11 - Default']: THREE.MeshStandardMaterial;
    ['03 - Default']: THREE.MeshStandardMaterial;
    ['01 - Default']: THREE.MeshStandardMaterial;
  };
};

export default function FrontWall(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(`${getPublicPath()}/3d/common/front-wall.glb`) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[3.12, 1.64, -9.39]} rotation={[Math.PI / 2, 0, 0]} scale={[0.005, 0.005, 0.005]}>
        <mesh material={materials['10 - Default']} geometry={nodes.Mesh003.geometry} />
        <mesh material={materials['11 - Default']} geometry={nodes.Mesh003_1.geometry} />
        <mesh material={materials['03 - Default']} geometry={nodes.Mesh003_2.geometry} />
        <mesh material={materials['01 - Default']} geometry={nodes.Mesh003_3.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload(`${getPublicPath()}/3d/common/front-wall.glb`);
