/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import { getPublicPath } from '../../../../utils/getPublicPath';

type GLTFResult = GLTF & {
  nodes: {
    Mesh016: THREE.Mesh;
    Mesh016_1: THREE.Mesh;
    Mesh016_2: THREE.Mesh;
    Mesh016_3: THREE.Mesh;
    Mesh016_4: THREE.Mesh;
    Mesh016_5: THREE.Mesh;
  };
  materials: {
    ['07 - Default2']: THREE.MeshStandardMaterial;
    ['15 - Default2']: THREE.MeshStandardMaterial;
    ['21 - Default']: THREE.MeshStandardMaterial;
    ['02 - Default']: THREE.MeshStandardMaterial;
    ['03 - Default.001']: THREE.MeshStandardMaterial;
    ['04 - Default']: THREE.MeshStandardMaterial;
  };
};

export default function LeftWall(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(`${getPublicPath()}/3d/common/left-wall.glb`) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-5.66, 3.61, 1.35]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 0.1]}>
        <mesh material={materials['07 - Default2']} geometry={nodes.Mesh016.geometry} />
        <mesh material={materials['15 - Default2']} geometry={nodes.Mesh016_1.geometry} />
        <mesh material={materials['21 - Default']} geometry={nodes.Mesh016_2.geometry} />
        <mesh material={materials['02 - Default']} geometry={nodes.Mesh016_3.geometry} />
        <mesh material={materials['03 - Default.001']} geometry={nodes.Mesh016_4.geometry} />
        <mesh material={materials['04 - Default']} geometry={nodes.Mesh016_5.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload(`${getPublicPath()}/3d/common/left-wall.glb`);
