import { IBlock } from "../types";
import { deg } from "../utils";

export const getCampusData = async () => {
  const fakeBlocks: IBlock[] = [
    {
      position: [-462, 367],
      dimensions: [160, 240],
      edgesHaveLights: ["up", "down", "left", "right"],
      edgesHaveTrees: ["left", "right"],
      buildings: [
        {
          id: "qwedwa",
          scale: 1,
          model: "b2",
          position: [-464, 407],
          rotationY: deg(90),
          name: "rust工作室",
        },
        {
          id: "xsaxsaffds",
          scale: 1,
          model: "b2",
          position: [-464, 317.1],
          rotationY: deg(90),
          name: "数据结构工作室",
        },
      ],
    },
    {
      position: [-263, 406],
      dimensions: [160, 160],
      edgesHaveLights: ["right"],
      edgesHaveTrees: [],
      buildings: [],
    },
    {
      position: [-263, 168.18],
      dimensions: [160, 240],
      edgesHaveLights: ["down"],
      edgesHaveTrees: ["right"],
      buildings: [],
    },
    {
      position: [-462, 128.3],
      dimensions: [160, 160],
      edgesHaveLights: ["up"],
      edgesHaveTrees: [],
      buildings: [
        {
          id: "dpasxosan",
          scale: 1,
          model: "b6",
          position: [-254, 227],
          rotationY: Math.PI / 2,
          name: "c++工作室",
        },
      ],
    },
    {
      position: [54, 207],
      dimensions: [345, 345],
      edgesHaveLights: ["up", "left", "right", "down"],
      edgesHaveTrees: ["up", "left", "right"],
      buildings: [
        {
          id: "xsadsa",
          scale: 1,
          model: "b7",
          position: [-31, 227],
          rotationY: deg(180),
          name: "c#工作室",
        },
        {
          id: "erwre",
          scale: 1,
          model: "b3",
          position: [131, 286],
          rotationY: deg(90),
          name: "c语言工作室",
        },
        {
          id: "qewqds",
          scale: 1,
          model: "b2",
          position: [131, 209],
          rotationY: deg(90),
          name: "python工作室",
        },
        {
          id: "sddsf",
          scale: 1,
          model: "b4",
          position: [112, 108],
          rotationY: deg(180),
          name: "nodejs工作室",
        },
      ],
    },
    {
      position: [392, 307],
      dimensions: [200, 280],
      edgesHaveLights: ["up", "left", "right", "down"],
      edgesHaveTrees: ["left", "right"],
      buildings: [
        {
          id: "fde$532",
          scale: 1,
          model: "b1",
          position: [372.5, 395.8],
          rotationY: deg(-90),
          name: "scratch工作室",
        },
        {
          id: "xasf55dx!",
          scale: 1,
          model: "b1",
          position: [372.5, 338.83],
          rotationY: deg(-90),
          name: "linux工作室",
        },
        {
          id: "fsd#fd6gc9",
          scale: 1,
          model: "b2",
          position: [383.17, 237.5],
          rotationY: deg(-90),
          name: "操作系统工作室",
        },
      ],
    },
    {
      position: [392, 28],
      dimensions: [200, 200],
      edgesHaveLights: ["up", "left", "right", "down"],
      edgesHaveTrees: ["left", "right"],
      buildings: [
        {
          id: "xxasdgrd",
          scale: 1,
          model: "b1",
          position: [452.7, 26.97],
          rotationY: deg(-90),
          name: "线性代数工作室",
        },
        {
          id: "xapsda",
          scale: 1,
          model: "b1",
          position: [452.7, -27.4],
          rotationY: deg(-90),
          name: "javascript工作室",
        },
        {
          id: "21fdfad",
          scale: 1,
          model: "b3",
          position: [373.22, 79.85],
          rotationY: deg(-90),
          name: "高等数学工作室",
        },
      
      ],
    },
    {
      position: [54, -110],
      dimensions: [320, 160],
      edgesHaveLights: ["up", "left", "right", "down"],
      edgesHaveTrees: ["left", "right"],
      buildings: [
        {
          id: "sfadsxcas",
          scale: 1,
          model: "b3",
          position: [-14.4, -91.4],
          name: "离散数学工作室",
        },
      ],
    },
    {
      position: [-363.3, -190],
      dimensions: [360, 320],
      edgesHaveLights: ["left", "down", "up", "right"],
      edgesHaveTrees: ["left", "up", "down"],
      buildings: [
        {
          id: "dsgdgrd",
          scale: 1,
          model: "b1",
          position: [-392.3, -140.8],
          rotationY: Math.PI / 2,
          name: "python工作室",
        },
        {
          id: "ytre",
          scale: 1,
          model: "b1",
          position: [-392.3, -83.4],
          rotationY: Math.PI / 2,
          name: "C++工作室",
        },
        {
          id: "csdvsd",
          scale: 1,
          model: "b4",
          position: [-253.5, -231.69],
          name: "java工作室",
        },
        {
          id: "gdfgfdg",
          scale: 1,
          model: "b2",
          position: [-357.6, -251],
          name: "C#工作室",
        },
        {
          id: "cdfgdfg",
          scale: 1,
          model: "b3",
          position: [-442.36, -251],
          name: "rust工作室",
        },
      ],
    },
    {
      position: [-462.8, -488.5],
      dimensions: [160, 200],
      edgesHaveLights: ["left", "down", "up", "right"],
      edgesHaveTrees: [],
      buildings: [
        {
          id: "csdfsdf",
          scale: 1,
          model: "b2",
          position: [-459, -468],
          name: "C工作室",
        },
      ],
    },
    {
      position: [-263, -488],
      dimensions: [160, 200],
      edgesHaveLights: ["down", "right"],
      edgesHaveTrees: ["up"],
      buildings: [
        {
          id: "gdgrd",
          scale: 1,
          model: "b3",
          position: [-229, -444],
          name: "jdk工作室",
        },
        {
          id: "cdcsdcsd",
          scale: 1,
          model: "b8",
          position: [-296, -538],
          name: "虚拟机工作室",
        },
      ],
    },
    {
      position: [54.5, -428.8],
      dimensions: [320, 320],
      edgesHaveLights: ["down", "right", "left"],
      edgesHaveTrees: ["down", "right", "left"],
      buildings: [
        {
          id: "csese",
          scale: 1,
          model: "b7",
          position: [60.4, -388.12],
          name: "nodejs工作室",
        },
        {
          id: "qwewqe",
          scale: 1,
          model: "b8",
          position: [-5.4, -495.3],
          name: "rust工作室",
        },
        {
          id: "2retret",
          scale: 1,
          model: "b2",
          position: [114.4, -497.45],
          name: "go工作室",
        },
      ],
    },
    {
      position: [392, -249],
      dimensions: [200, 280],
      edgesHaveLights: ["down", "right", "left"],
      edgesHaveTrees: ["right", "left"],
      buildings: [
        {
          id: "hgfghffg",
          scale: 1,
          model: "b3",
          position: [385.8, -195.1],
          rotationY: deg(-90),
          name: "go工作室",
        },
        {
          id: "vfdvd",
          scale: 1,
          model: "b2",
          position: [385.8, -309.9],
          rotationY: deg(-90),
          name: "C++工作室",
        },
      ],
    },
    {
      position: [392, -508],
      dimensions: [200, 160],
      edgesHaveLights: ["down", "right", "left"],
      edgesHaveTrees: [],
      buildings: [],
    },
  ];
  return fakeBlocks;
};
