/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, useState, useEffect } from 'react';
import { useFrame } from 'react-three-fiber';
import { useGLTF } from '@react-three/drei';

import { useAnimations } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    Book_0: THREE.Mesh;
  };
  materials: {
    Base: THREE.MeshStandardMaterial;
  };
};

type ActionName = 'Take 01_Armature' | 'Take 01';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Book2(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF('./public/3d/book/b2.glb') as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log('actions', actions);
    actions['Take 01'].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='RootNode_(gltf_orientation_matrix)'>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-0.06, -0.02, -0.02]} rotation={[-Math.PI, 0, 0]}>
            <group position={[0, 0.44, 0]} rotation={[0, 0, 0]}>
              <group position={[0, 0.43, 0]} rotation={[0, 0, 0]}>
                <group position={[0, 0.43, 0]} rotation={[0, 0, 0]} />
              </group>
            </group>
          </group>
          <group position={[0.06, -0.02, -0.02]} rotation={[-Math.PI, 0, 0]}>
            <group position={[0, 0.44, 0]} rotation={[0, 0, 0]}>
              <group position={[0, 0.43, 0]} rotation={[0, 0, 0]}>
                <group position={[0, 0.43, 0]} rotation={[0, 0, 0]} />
              </group>
            </group>
          </group>
          <group position={[0, 0.12, -0.02]} rotation={[-Math.PI, 0, 0]}>
            <group position={[0, 0.11, 0]} rotation={[-Math.PI / 2, -0.49, -Math.PI / 2]} />
            <group
              position={[0, 0.11, 0]}
              rotation={[-Math.PI / 2, 0.49, Math.PI / 2]}
              scale={[1, 1, 1]}
            />
          </group>
        </group>
        <mesh material={materials.Base} geometry={nodes.Book_0.geometry} />
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} scale={[1, 1, 1]} />
      </group>
    </group>
  );
}

useGLTF.preload('./public/3d/book/b2.glb');
